CREATE TABLE event_registration (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT NOT NULL,
    person_id       BIGINT NOT NULL,
    registered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_event_registration_event
        FOREIGN KEY (event_id) REFERENCES event(id),

    CONSTRAINT fk_event_registration_person
        FOREIGN KEY (person_id) REFERENCES person(id),

    CONSTRAINT uq_event_person UNIQUE (event_id, person_id)
);