spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    time-zone: Europe/Tallinn

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  admin:
    username: admin
    password: 1234
    role: ADMIN
  jwt:
    secret: verysecretkey123verysecretkey123
    expiration-ms: 86400000